### PR TITLE
[ENH] fix #173 - do not hide mouse cursor if in debug mode

### LINKED ISSUE #173: [ENH]: if debug mode do not hide the cursor
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

```markdown
This is useful in the case the user is debugging the code putting matlab as well in debug mode and running step (line) by step
```

### Unclear documentation

_No response_

### PR DESCRIPTION
**Pull request by marcobarilari**

### CODE REVIEW

**Comment by marcobarilari** [comment]
close #173

**Review by Remi-Gau — COMMENTED** [review]
how about having a "hideCursor" in the config and making sure it is set to false when in debug mode?

**Comment by marcobarilari** [comment]
makes sense

**Comment by Remi-Gau** [comment]
changed the base branch to point to the one where are making changes

**Pull request closed without merging**
